# Generated by Django 5.2.6 on 2025-10-20 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTaxCertificate',
            fields=[
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appointments.appointment')),
                ('address', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=20)),
                ('citizenship', models.CharField(max_length=50)),
                ('occupation_or_business', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateOfIndigency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
        ),
    ]
