# Generated by Django 5.2.6 on 2025-10-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_communitytaxcertificate_certificateofindigency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytaxcertificate',
            name='date_of_birth',
        ),
    ]
